package formularios;

import BD.ConexionBD;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    private String cedula = "";    

    public Login() {
        initComponents();
        setTitle("Login");
        setSize(665, 560);
        setResizable(false);
        setLocationRelativeTo(null);
        javax.swing.Timer t = new javax.swing.Timer(1000, (ActionEvent e) -> {
            Date fecha = new Date();
            SimpleDateFormat dt = new SimpleDateFormat("E, dd/MM/yyyy");
            String fechaa = dt.format(fecha);
            FechaActual.setText(fechaa);
            dt = new SimpleDateFormat("HH:mm:ss");
            String hora = dt.format(fecha);
            HoraActual.setText(hora);
        });
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        txt_contraseña = new javax.swing.JPasswordField();
        btn_ingresar = new javax.swing.JButton();
        btn_registrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        FechaActual = new javax.swing.JFormattedTextField();
        HoraActual = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro De Asistencia Docente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 314, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Contraseña");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cédula");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, 20));

        txt_cedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 210, -1));

        txt_contraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 210, -1));

        btn_ingresar.setBackground(new java.awt.Color(0, 0, 0));
        btn_ingresar.setForeground(new java.awt.Color(255, 255, 255));
        btn_ingresar.setText("Ingresar");
        btn_ingresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_ingresar.setBorderPainted(false);
        btn_ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 80, 30));

        btn_registrar.setForeground(new java.awt.Color(0, 0, 0));
        btn_registrar.setText("Registrar");
        btn_registrar.setBorderPainted(false);
        btn_registrar.setContentAreaFilled(false);
        btn_registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FechaActual.setEditable(false);
        FechaActual.setBackground(new java.awt.Color(255, 255, 255));
        FechaActual.setBorder(null);
        FechaActual.setForeground(new java.awt.Color(0, 0, 0));
        FechaActual.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        FechaActual.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FechaActual.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel2.add(FechaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 20, 240, 51));

        HoraActual.setEditable(false);
        HoraActual.setBackground(new java.awt.Color(255, 255, 255));
        HoraActual.setBorder(null);
        HoraActual.setForeground(new java.awt.Color(0, 0, 0));
        HoraActual.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        HoraActual.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jPanel2.add(HoraActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 80, 350, 51));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 470, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        String cedula = txt_cedula.getText().trim(), contraseña = txt_contraseña.getText().trim();

        if (cedula.equals("") || contraseña.equals("")) {
            JOptionPane.showMessageDialog(this, "Debe ingresar todos los datos");
        } else {
            try {
                Connection cn = ConexionBD.conectar();
                PreparedStatement ps = cn.prepareStatement("select cedula, contraseña from docentes where cedula = '"
                        + cedula + "' and contraseña = '" + contraseña + "'");
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    ps = cn.prepareStatement("select cedula, jornada_manana from docentes where cedula = '" + cedula + "' and not length(jornada_manana) = 0");
                    rs = ps.executeQuery();
                    if (rs.next()) {
                        RegEntradaSalida registro = new RegEntradaSalida(cedula);
                        registro.setVisible(true);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "No tiene un horario registrado");
                    }

                } else {
                    PreparedStatement ps2 = cn.prepareStatement("select * from administradores where cedula = '"
                            + cedula + "' and contraseña = '" + contraseña + "'");
                    ResultSet rs2 = ps2.executeQuery();
                    if (rs2.next()) {
                        DocentesRegistrados docentes = new DocentesRegistrados();
                        txt_cedula.setText("");
                        txt_contraseña.setText("");
                        docentes.setVisible(true);
                       
                    } else {
                        JOptionPane.showMessageDialog(this, "Cedula o contraseña incorrectos");
                    }
                }
            } catch (SQLException e) {
                System.err.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        RegistroDocente docente = new RegistroDocente();
        docente.setVisible(true);
    }//GEN-LAST:event_btn_registrarActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField FechaActual;
    private javax.swing.JFormattedTextField HoraActual;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JPasswordField txt_contraseña;
    // End of variables declaration//GEN-END:variables
}
